### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by trdwll** [trdwll/avocado#12]
This should be easy. lol Just something simple that will fit the project well.

**Comment by DigitalDesignerOnline** [comment]
will get on it right awaay, any creative direction you want to send my way so that I can make something we are both proud of :)

**Comment by trdwll** [comment]
@DigitalDesignerOnline Honestly, I'm terrible at design/ideas for design. As generic and cliche it sounds, but what do you think about an icon of an avocado? lol

**Comment by DigitalDesignerOnline** [comment]
on it mate with a bit of typography, after all sometimes the most obvious answer is the right answer :) will shoot you something shortly :)

**Comment by DigitalDesignerOnline** [comment]
![avocado-concepts](https://user-images.githubusercontent.com/25376856/31207951-4fb17886-a94f-11e7-9d80-31ee361ff83e.jpg)
Check out the two concepts and let me know which direction you are leaning towards, I will enhance the graphic you choose or go back to the drawing board for another round ;)

**Comment by trdwll** [comment]
I really like both. haha the bottom one is best out of the two though. @DigitalDesignerOnline

**Comment by DigitalDesignerOnline** [comment]
ok I can edit it how you see fit, or if you want it as is shoot you the high res and psd file etc so you have it for future use as well on other platforms.

**Comment by trdwll** [comment]
I think it looks great as is, but if you have any other ideas to improve it even more then feel free.

**Comment by DigitalDesignerOnline** [comment]
you got it mate give me 5 mins and I will send it all off to you. woot woot my first contribution to #Hacktoberfest lol

**Comment by trdwll** [comment]
Make sure you send it as a PR so you can get the stickers and even possibly the shirt. 😃 (if you're wanting to get them :p)

**Comment by DigitalDesignerOnline** [comment]
to be honest not sure how, will have to read up on that part I guess, still new to the community and just wanting to contribute to the event :)

**Comment by DigitalDesignerOnline** [comment]
but yeah the shirt would be sweet :) stickers are always fun too

**Comment by trdwll** [comment]
@DigitalDesignerOnline Did you sign up via https://hacktoberfest.digitalocean.com/ (this page will describe everything regarding the event)? If so then go to the top of the page and click "Fork". Then read this https://help.github.com/articles/creating-a-pull-request-from-a-fork/. Basically after you fork avocado you're going to want to add the psd to the repo then do a PR (link above).

**Comment by DigitalDesignerOnline** [comment]
I signed up there, and have now created a fork, added the files and created the pull request, I hope I did it all right for the credit but either way happy to assist

**Comment by trdwll** [comment]
Merged! :D This tool (https://hacktoberfestchecker.herokuapp.com/) is unofficial, but it can tell you how many PRs you need (if you don't remember) until you get a tshirt (4).  On the event page (the digitalocean link) it says "To get a shirt, you must make four pull requests between October 1–31 in any timezone."

Thanks for the logo, really appreciate it.
