### ISSUE TITLE
Readme Badges

### ISSUE THREAD

**Issue by trdwll** [trdwll/avocado#13]
Add some badges for the license, issues, forks, stars, downloads, and anything else that you think should be added also.

**Comment by rivermont** [comment]
I'll add some of these sometime tonight.

**Comment by rivermont** [comment]
[Here ya go](https://github.com/trdwll/avocado/pull/14)!

**Comment by trdwll** [comment]
Looks great, merged.

**Comment by trdwll** [comment]
Care to add stars? @rivermont
