### ISSUE TITLE
Cleanup HTTP Error Templates

### ISSUE THREAD

**Issue by trdwll** [trdwll/avocado#21]
Rewrite the errors on the error pages to something that all users will understand.

[These](https://github.com/trdwll/avocado/tree/master/avocado/templates/error_pages) templates.

**Comment by h93xV2** [comment]
I would like to work on this.

**Comment by cgarciahdez** [comment]
Hi! I'm interested to take over this issue, but I was wondering exactly what you would like the error pages to say. I see that now they're trying to be more funny than anything else. Would they ideally be more generic and explain why each of the errors could've potentially been generated?

**Comment by trdwll** [comment]
@cgarciahdez More generic to help the end user understand what has occurred.

**Comment by cgarciahdez** [comment]
@trdwll Great! I'll get working on it if that's ok, then?
